### ISSUE TITLE
None of it works as the extensions need to target the IPage interface instead

### ISSUE THREAD

**Issue by strich** [hlaueriksson/puppeteer-sharp-contrib#17]
Not sure when things changed but as of PuppeteerSharp v12 everything is done by interfaces ie `IPage` and `IBrowser`. This whole library is broken and not working as it targets the concrete objects of `Page` etc.

**Comment by hlaueriksson** [comment]
@strich thanks for reporting this issue!

It probably broke in [v8.0.0](https://github.com/hardkoded/puppeteer-sharp/releases/tag/v8.0.0) (Oct 6, 2022) when [Implement Interfaces for public API](https://github.com/hardkoded/puppeteer-sharp/pull/1965) was introduced.

I will take a look at this.

**Comment by hlaueriksson** [comment]
You can try the fix for this in version `6.0.0`:

- https://github.com/hlaueriksson/puppeteer-sharp-contrib/releases/tag/v6.0.0
- https://www.nuget.org/packages/PuppeteerSharp.Contrib.Extensions/6.0.0
- https://www.nuget.org/packages/PuppeteerSharp.Contrib.Should/6.0.0
- https://www.nuget.org/packages/PuppeteerSharp.Contrib.PageObjects/6.0.0

**Comment by hlaueriksson** [comment]
I'm closing this issue now as fixed.

@strich If you have any more issues with this, please comment and I can reopen it.
